/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Fes-Suporte
 */
public class JMainAdmin extends javax.swing.JFrame {

    private Integer cod_funcionario;

    public Integer getCod_funcionario() {
        return cod_funcionario;
    }

    public void setCod_funcionario(Integer cod_funcionario) {
        this.cod_funcionario = cod_funcionario;
    }
    
    public JMainAdmin() {
        initComponents();
    }

    public void openWindow(JInternalFrame tela){
        Boolean exist = false;
        for(JInternalFrame internal: jDesktopAdmin.getAllFrames()){
            if(internal.getClass().toString().equalsIgnoreCase(tela.getClass().toString())){
                internal.moveToFront();
                exist = true;
            }
        }
        if(!exist){
            jDesktopAdmin.add(tela);
            tela.setVisible(true);
            tela.setClosable(true);
            tela.setIconifiable(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopAdmin = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenuItem();
        jMenuFuncionario = new javax.swing.JMenuItem();
        jMenuFornecedor = new javax.swing.JMenuItem();
        jEstoque = new javax.swing.JMenu();
        jVenda = new javax.swing.JMenu();
        jHistorico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopAdminLayout = new javax.swing.GroupLayout(jDesktopAdmin);
        jDesktopAdmin.setLayout(jDesktopAdminLayout);
        jDesktopAdminLayout.setHorizontalGroup(
            jDesktopAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopAdminLayout.setVerticalGroup(
            jDesktopAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopAdmin, java.awt.BorderLayout.CENTER);

        jCadastro.setText("Cadastro");

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jCadastro.add(jMenuCliente);

        jMenuProduto.setText("Produto");
        jMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutoActionPerformed(evt);
            }
        });
        jCadastro.add(jMenuProduto);

        jMenuFuncionario.setText("Funcionario");
        jMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuncionarioActionPerformed(evt);
            }
        });
        jCadastro.add(jMenuFuncionario);

        jMenuFornecedor.setText("Fornecedor");
        jMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFornecedorActionPerformed(evt);
            }
        });
        jCadastro.add(jMenuFornecedor);

        jMenuBar1.add(jCadastro);

        jEstoque.setText("Estoque");
        jEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEstoqueMouseClicked(evt);
            }
        });
        jEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEstoqueActionPerformed(evt);
            }
        });
        jMenuBar1.add(jEstoque);

        jVenda.setText("Venda");
        jVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVendaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jVenda);

        jHistorico.setText("Histórico");
        jHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHistoricoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jHistorico);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuncionarioActionPerformed
        JInternalFuncionario jf = new JInternalFuncionario();
        openWindow(jf);
    }//GEN-LAST:event_jMenuFuncionarioActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        JInternalCliente jf = new JInternalCliente();
        openWindow(jf);
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutoActionPerformed
        JInternalProduto jf = new JInternalProduto();
        openWindow(jf);
    }//GEN-LAST:event_jMenuProdutoActionPerformed

    private void jMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFornecedorActionPerformed
        JInternalFornecedor jf = new JInternalFornecedor();
        openWindow(jf);
    }//GEN-LAST:event_jMenuFornecedorActionPerformed

    private void jEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEstoqueActionPerformed
        
    }//GEN-LAST:event_jEstoqueActionPerformed

    private void jEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEstoqueMouseClicked
        JInternalEstoque jf = new JInternalEstoque();
        openWindow(jf);
    }//GEN-LAST:event_jEstoqueMouseClicked

    private void jVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVendaMouseClicked
        JInternalVenda jf = new JInternalVenda();
        openWindow(jf);
        jf.cod_func = cod_funcionario;
    }//GEN-LAST:event_jVendaMouseClicked

    private void jHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHistoricoMouseClicked
        JInternalHistorico jf = new JInternalHistorico();
        openWindow(jf);
    }//GEN-LAST:event_jHistoricoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCadastro;
    protected static javax.swing.JDesktopPane jDesktopAdmin;
    private javax.swing.JMenu jEstoque;
    private javax.swing.JMenu jHistorico;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuFornecedor;
    private javax.swing.JMenuItem jMenuFuncionario;
    private javax.swing.JMenuItem jMenuProduto;
    private javax.swing.JMenu jVenda;
    // End of variables declaration//GEN-END:variables
}
